### PR TITLE
Formalism Operation (Test issue)

### PR DESCRIPTION
**Pull request by Seriane**
This is a first version of the formalism that we implemented, you can find in the operation directory, the file "operation.lua" and "operation.test.lua", where the problem is: It seems that the checks are not done when an attribute has a formalism type, besides the literal one (String,Number,Bool,Identifier).
ps: (some expression and  operation formalisms are not verified yet).

### CODE REVIEW

**Comment by saucisson** [comment]
First thing to do: remove all the `luacheck` warnings, please.

**Comment by Seriane** [comment]
All the warnings have been removed.

**Comment by saucisson** [comment]
OK, now the rockspec file is lacking a `dependencies` section. You can for instance add:

```lua
dependencies = {
  "lua >= 5.1",
  "layeredata",
  "coronest",
}
```

**Comment by saucisson** [comment]
Now all checks pass... so where is the problem?

**Comment by Seriane** [comment]
We added a file containing a log showing a segmentation error from the execution of the test script (dump.txt).

**Pull request closed without merging**
